apiVersion: v1
kind: Service
metadata:
  namespace: selenium
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: port0
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  namespace: selenium
  name: selenium-hub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: selenium-hub
spec:
  rules:
  - host: "hub.9f7e5668-5cd5-482a-b441-0ebc0adc47c6.nodes.k8s.fr-par.scw.cloud"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: selenium-hub
            port:
              number: 4444